In [2]:
#Import
import numpy as np

In [3]:
#Variable Arr
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#Slice The variable arr
#Create a new variable called slice_arr
#Get The Exact Position
slice_arr = arr[0:6]

In [14]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_arr[:] = 99

In [16]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
# Goal is to not change the arr variable
# Create a new variable called arr_copy
# Copy it with arr.copy()
arr_copy = arr.copy()

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy[:] = 200

In [21]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [22]:
# It does not change!
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
#mat[row,col]
#mat[row][col]

In [24]:
# Mat is the Variable that stands for matrix
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
mat[0]

array([ 5, 10, 15])

In [27]:
mat[2]

array([35, 40, 45])

In [28]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
# Option 1 to index matrixes
mat[1][1]

25

In [30]:
# Option 2 to index matrixes
mat[1,1]

25

In [31]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
mat[0,2]

15

In [33]:
# Precise Positioning
# Remember: mat[row,col]
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [34]:
# Index 20,25 and 35,40
mat[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [35]:
#Final Step
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [36]:
#Conditional Selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
#Make A Variable Called Bool_arr and Store data above 4.
bool_arr = arr > 4

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
#Other Way
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr[arr<=9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])